defconfig: sedona: enable CONFIG_FOGOS_DTB missing
fix it
Traceback (most recent call last):
  File "/home/runner/work/build/build/android_kernel_motorola_sedona/out/../scripts/mkdtboimg.py", line 1002, in <module>
    main()
  File "/home/runner/work/build/build/android_kernel_motorola_sedona/out/../scripts/mkdtboimg.py", line 999, in main
    subcmd.func(subcmd.argfile, subcmd_args)
  File "/home/runner/work/build/build/android_kernel_motorola_sedona/out/../scripts/mkdtboimg.py", line 808, in create_dtbo_image
    raise ValueError('List of dtimages to add to DTBO not provided')
ValueError: List of dtimages to add to DTBO not provided

Signed-off-by: Barry <barryofc11@gmail.com>